import type { Metadata } from "next";
import "./globals.css";
import { Unbounded } from 'next/font/google';

const unbounded = Unbounded({
  subsets: ['latin'],
  variable: '--font-unbounded',
  display: 'swap',
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={`${unbounded.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
